=== yagee97/WebProgramming/EX1/bulletin.dtd
<!ELEMENT board (name,(article+))>
<!ELEMENT name (#PCDATA)>
<!ELEMENT article (title,message,writerID,writerName,(reply*))>
<!ELEMENT title (#PCDATA)>
<!ELEMENT message (#PCDATA)>
<!ELEMENT writerID (#PCDATA)>
<!ELEMENT writerName (#PCDATA)>
<!ELEMENT reply (message,writerID,writerName)>

=== yagee97/WebProgramming/EX2_4/ex2_4_c/bulletin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE board SYSTEM "bulletin.dtd">
<board>
	<name>BOARD</name>
	<article>
		<title>GOWEB</title>
		<message>FIGHTING</message>
		<writerID>201635838</writerID>
		<writerName>YEJI</writerName>
		<reply>
			<message>HEY</message>
			<writerID>201635838</writerID>
			<writerName>YEJI</writerName>
		</reply>
	</article>
</board>
